In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1XkmqBOy7i9WgzXeM9TUhfC9Eioe-nSLY')

     |████████████████████████████████| 71kB 3.5MB/s 


# 5 Interesting Pytorch Functions

PyTorch is a free and open source machine learning framework primarily developed by Facebook's AI Research lab (FAIR) used for applications such as natural language processing and computer vision. The following functions shall be used as examples for showcasing the awesomeness that is pytorch. 

- torch.eye
- torch.chunk
- torch.t
- torch.movedim
- torch.floor

Before we begin, let's install and import PyTorch

In [2]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.eye
This function returns a 2-D tensor with ones on the diagonal and zeros elsewhere.

In [3]:
t1= torch.eye(7)
t1

tensor([[1., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 1.]])

Returns the number of `1s` specified in diagonal form and `0s` elsewhere. That means `7` specifies `7` `1s`, `7` rows and `7` columns if nothing else is defined.

In [4]:
t2=torch.eye(n=5,m=3)
t2

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 0., 0.],
        [0., 0., 0.]])

`t2` returns a tensor with `1` on the diagonal according the the number of specified and `0` in other places. Where `n` is `int` and represents the number of rows and `m` is `int` and represents the number of columns. If `m` is not specified, the default number of columns will be the same as `n`.

In [5]:
t3=torch.eye(3.4)

TypeError: ignored

The error which caused the function to break was caused by a wrong input of a `float` instead of an `int`. In order to correct the error, an `int` should be used.

Can be used when you want a matrix made up of only `1s` and `0s` with only the `1s` as the diagonal.

Let's save our work using Jovian before continuing.

In [6]:
import jovian

In [8]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tdogubo/01-tensor-operations


'https://jovian.ai/tdogubo/01-tensor-operations'

## Function 2 - torch.chunk

Splits a tensor into a specified number of `chunks`.

In [9]:
array= np.random.rand(10,8)
t4= torch.tensor(array)
torch.chunk(t4,chunks=2)

(tensor([[0.3045, 0.6568, 0.0168, 0.6546, 0.6669, 0.3048, 0.9405, 0.7678],
         [0.1959, 0.2115, 0.1587, 0.3965, 0.8109, 0.8855, 0.3663, 0.7879],
         [0.3900, 0.7195, 0.2936, 0.0038, 0.4007, 0.9123, 0.5969, 0.5127],
         [0.4469, 0.0045, 0.8723, 0.4075, 0.4436, 0.6354, 0.3035, 0.7578],
         [0.7175, 0.0156, 0.3618, 0.1916, 0.7163, 0.4546, 0.8116, 0.1065]],
        dtype=torch.float64),
 tensor([[0.1627, 0.4300, 0.6339, 0.6831, 0.0658, 0.2684, 0.1673, 0.4152],
         [0.0204, 0.1030, 0.1350, 0.8292, 0.5907, 0.0137, 0.5460, 0.2489],
         [0.2135, 0.6857, 0.8820, 0.6161, 0.7198, 0.3271, 0.4453, 0.9661],
         [0.2173, 0.3634, 0.8845, 0.1074, 0.0177, 0.1607, 0.9584, 0.4972],
         [0.1848, 0.4776, 0.8929, 0.1867, 0.6230, 0.6168, 0.5298, 0.6244]],
        dtype=torch.float64))

`torch.chunk` on `t4` and specifying the number of `chunks`, `2`,split the larger `t4` tensor into `2` smaller tensors or `chunks`. 

In [10]:
torch.chunk(torch.randn((5,5)), chunks=3)

(tensor([[ 0.2290,  0.3296,  1.1069, -0.3029, -0.6434],
         [-0.4924, -1.2191, -0.1836,  1.5504, -0.1623]]),
 tensor([[ 0.8254,  0.8015,  0.6716, -1.1041,  0.6485],
         [ 1.0015, -0.9533, -0.8745,  0.0560,  1.2811]]),
 tensor([[ 0.7831, -0.0852, -0.0558,  0.4838,  0.3332]]))

The tensor with the shape `(5,5)` was split into `3` chunks, the first two having an equal number of rows and columns `(2,5)` each and the last having the remaining 1 row and 5 columns .`(2,5) + (2,5) + (1,5) = (5,5)` 

In [11]:
array2= np.random.random_sample((5,5))
torch.chunk(array2,chunk=5)

TypeError: ignored

The input given for the operation has to be a tensor, or in tensor form else, an error will occur.

Can be used when spliting a large tensor into smaller groups while still maintaining the original size.

In [12]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tdogubo/01-tensor-operations


'https://jovian.ai/tdogubo/01-tensor-operations'

## Function 3 - torch.t

Converts a 2-dimensional tensor and transposes dimensions `0` and `1`.

In [13]:
t5= torch.rand(1,3)
t5

tensor([[0.5477, 0.3472, 0.5137]])

In [14]:
torch.t(t5)

tensor([[0.5477],
        [0.3472],
        [0.5137]])

`torch.t` converted the `2D` Tensor, `1` column and `3` rows to a tensor with `3` rows and `1` column.

In [15]:
t6= torch.rand(2,10)
t6

tensor([[0.2446, 0.7120, 0.2166, 0.8870, 0.8762, 0.8191, 0.4769, 0.2140, 0.0050,
         0.9812],
        [0.9207, 0.7100, 0.8306, 0.5188, 0.9461, 0.2947, 0.8578, 0.4882, 0.0801,
         0.3850]])

In [16]:
torch.t(t6)

tensor([[0.2446, 0.9207],
        [0.7120, 0.7100],
        [0.2166, 0.8306],
        [0.8870, 0.5188],
        [0.8762, 0.9461],
        [0.8191, 0.2947],
        [0.4769, 0.8578],
        [0.2140, 0.4882],
        [0.0050, 0.0801],
        [0.9812, 0.3850]])

The dimensions `0` and `1` in the tensor with size `(2,10)` were transposed to `(10,2)`.

In [17]:
t7= torch.rand(2,5,3)
torch.t(t7)

RuntimeError: ignored

`torch.t` takes only a `2D` tensor input. Once an input other than that is given, the code breaks.

Can be used when peforming mathematical functions on `2D` tensors having only one `n-dimensions` in common.

In [18]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tdogubo/01-tensor-operations


'https://jovian.ai/tdogubo/01-tensor-operations'

## Function 4 - torch.movedim
Swaps the dimensions of the specified input.

In [19]:
t7, t7.shape

(tensor([[[0.8323, 0.8677, 0.6070],
          [0.2722, 0.2819, 0.2909],
          [0.6891, 0.8325, 0.9842],
          [0.9033, 0.3702, 0.7742],
          [0.7925, 0.2935, 0.2271]],
 
         [[0.3021, 0.6506, 0.4546],
          [0.1959, 0.8389, 0.5252],
          [0.5334, 0.9954, 0.7350],
          [0.5527, 0.7025, 0.2297],
          [0.9180, 0.0738, 0.3711]]]), torch.Size([2, 5, 3]))

In [20]:
torch.movedim(t7,0,1), torch.movedim(t7,0,1).shape

(tensor([[[0.8323, 0.8677, 0.6070],
          [0.3021, 0.6506, 0.4546]],
 
         [[0.2722, 0.2819, 0.2909],
          [0.1959, 0.8389, 0.5252]],
 
         [[0.6891, 0.8325, 0.9842],
          [0.5334, 0.9954, 0.7350]],
 
         [[0.9033, 0.3702, 0.7742],
          [0.5527, 0.7025, 0.2297]],
 
         [[0.7925, 0.2935, 0.2271],
          [0.9180, 0.0738, 0.3711]]]), torch.Size([5, 2, 3]))

The 1st and 2nd dimensions were swapped. So, the original shape of `(2,5,3)` changed to `(5,2,3)`. 

In [21]:
t8= torch.rand(2,3,1)
t8

tensor([[[0.3803],
         [0.7869],
         [0.2747]],

        [[0.8649],
         [0.0683],
         [0.1488]]])

In [22]:
torch.movedim(t8,(2,1),(0,1)), torch.movedim(t8,(2,1),(0,1)).shape

(tensor([[[0.3803, 0.8649],
          [0.7869, 0.0683],
          [0.2747, 0.1488]]]), torch.Size([1, 3, 2]))

In the example, the dimensions to be moved, `(2,1)` were moved to the destination `(0,1)`. Because `dimension 1` destination was not changed, the tensors remained unchanged. Hence the shape `(2,3,1)` changed to `(1,3,2)`.

In [23]:
torch.movedim(array)

TypeError: ignored

The function only accepts a tensor as the input. If any other input aside from a tensor is given, the function breaks.

Can be used when you want to change the shape of a tensor without altering the contents. Unlike `torch.t`, `torch.movedim` is not limited to `2D` tensors only.

In [24]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tdogubo/01-tensor-operations


'https://jovian.ai/tdogubo/01-tensor-operations'

## Function 5 - torch.floor
Rounds the tensors to the lowest possible number.

In [25]:
t9= torch.tensor([[1.0, 1.9, 4.5, 2],
        [5, 3, 1, 4],
        [2, 3, 1, 1]])
t9

tensor([[1.0000, 1.9000, 4.5000, 2.0000],
        [5.0000, 3.0000, 1.0000, 4.0000],
        [2.0000, 3.0000, 1.0000, 1.0000]])

In [26]:
torch.floor(t9)

tensor([[1., 1., 4., 2.],
        [5., 3., 1., 4.],
        [2., 3., 1., 1.]])

`torch.floor` rounded down the numbers to the lowest possible number to zero.

In [27]:
t10= torch.tensor([2.4,-7.6,3.4,-5.3,6.9,-0.9])
t10

tensor([ 2.4000, -7.6000,  3.4000, -5.3000,  6.9000, -0.9000])

In [28]:
torch.floor(t10)

tensor([ 2., -8.,  3., -6.,  6., -1.])

`torch.floor` rounded down both the negative and positive numbers.

In [29]:
t11= torch.randint(2,15,(3,9))
t11

tensor([[ 7, 12,  9,  7, 11, 11, 11,  4, 13],
        [12,  2,  3,  6, 13, 13,  2,  4,  8],
        [13,  2, 14,  9,  6, 13,  5, 13,  9]])

In [30]:
torch.floor(t11)

RuntimeError: ignored

`torch.floor` can only be used with `float` if an `int` is the input, an error pops up. 

Closing comments about when to use this function

In [31]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tdogubo/01-tensor-operations


'https://jovian.ai/tdogubo/01-tensor-operations'

## Conclusion


1.   `torch.eye` returns a 2-D tensor with ones on the diagonal and zeros elsewhere.
2.   `torch.chunk` splits a tensor into a specified number of `chunks`.
3. `torch.t` converts a 2-dimensional tensor and transposes dimensions `0` and `1`.
4. `torch.movedim` swaps the dimensions of the specified input.
5. `torch.ceil` rounds the tensors to the lowest possible number.


## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* GeeksforGeeks : [geeksforgeeks.org/python-pytorch-eye-method/](https://geeksforgeeks.org/python-pytorch-eye-method/)

*  Floor and Celing Functions : [https://en.wikipedia.org/wiki/Floor_and_ceiling_functions](https://en.wikipedia.org/wiki/Floor_and_ceiling_functions)

In [ ]:
jovian.commit(project='01-tensor-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/tdogubo/01-tensor-operations


'https://jovian.ai/tdogubo/01-tensor-operations'